#!/usr/bin/env bash
# generate-ui-verify-spec.sh — translate entity's render_fidelity_targets[] to
# ui-verify YAML spec (ship-flow:ui-verify).
#
# Background: PR #44 ship-verify Step 3.6 dispatches `Skill: ship-flow:ui-verify` with
# render_fidelity_targets as input. ui-verify expects its own YAML schema
# (.claude/e2e/ui-verify/<slug>.yaml). This script bridges the formats.
#
# Usage:
#   bash generate-ui-verify-spec.sh <entity-folder> <mapping-name> [auth-account]
#
# Output (stdout): ready-to-write YAML for .claude/e2e/ui-verify/<entity-slug>.yaml
#
# Exit codes:
#   0 — spec generated (or design-skipped, emits empty-spec marker)
#   1 — render_fidelity_targets[] missing or in legacy prose format
#   2 — usage error
#
# Field mapping:
#   render_fidelity_target.selector       → ui-verify check.selector
#   render_fidelity_target.css_property   → ui-verify check.expect.<camelCase> key
#   render_fidelity_target.expected_value → ui-verify check.expect.<camelCase> value
#   render_fidelity_target.rationale_decision (D{N}) → ui-verify check.name prefix

set -euo pipefail

ENTITY_DIR="${1:-}"
MAPPING="${2:-}"
AUTH="${3:-}"

[ -z "$ENTITY_DIR" ] && { echo "ERROR: usage: $0 <entity-folder> <mapping-name> [auth-account]" >&2; exit 2; }
[ -z "$MAPPING" ] && { echo "ERROR: <mapping-name> required (filename without .yaml in .claude/e2e/mappings/)" >&2; exit 2; }

if [ -d "$ENTITY_DIR" ]; then
  ENTITY_FILE="${ENTITY_DIR%/}/README.md"
  [ -f "$ENTITY_FILE" ] || ENTITY_FILE="${ENTITY_DIR%/}/design.md"
elif [ -f "$ENTITY_DIR" ]; then
  ENTITY_FILE="$ENTITY_DIR"
else
  echo "ERROR: target not found: $ENTITY_DIR" >&2; exit 2
fi
[ -f "$ENTITY_FILE" ] || { echo "ERROR: entity file not found: $ENTITY_FILE" >&2; exit 2; }

# Extract title for ui-verify YAML
ENTITY_ID=$(basename "$(dirname "$ENTITY_FILE")")
TITLE=$(grep -m1 -E '^title:|^# ' "$ENTITY_FILE" 2>/dev/null \
  | head -1 | sed -E 's/^title:[[:space:]]*"?([^"]*)"?[[:space:]]*$/\1/; s/^#[[:space:]]+//' \
  || echo "$ENTITY_ID")

# Extract Hand-off to Plan block
HANDOFF=$(awk '/^### Hand-off to Plan/{flag=1} /^<!-- \/section:hand-off-to-plan -->/{flag=0} flag' "$ENTITY_FILE")

if [ -z "$HANDOFF" ]; then
  echo "ERROR: '### Hand-off to Plan' block not found in $ENTITY_FILE" >&2
  exit 1
fi

# Design-skipped short-circuit
if echo "$HANDOFF" | grep -qE '^[[:space:]]*-?[[:space:]]*design-skipped:[[:space:]]*true'; then
  echo "# ui-verify spec skipped: entity has design-skipped:true (no UI surface)"
  echo "# Generated by plugins/ship-flow/lib/generate-ui-verify-spec.sh from $ENTITY_FILE"
  exit 0
fi

# Format detection
STRUCTURED_HINTS=$(echo "$HANDOFF" | grep -cE '^[[:space:]]+(selector|css_property|expected_value):' || true)
if [ "$STRUCTURED_HINTS" -lt 2 ]; then
  echo "ERROR: render_fidelity_targets[] not in structured format (PR #44 schema)." >&2
  echo "ERROR: Run: bash plugins/ship-flow/lib/migrate-design-constraints.sh $ENTITY_FILE" >&2
  exit 1
fi

# Helper: kebab-to-camel for CSS property names (background-color → backgroundColor)
kebab_to_camel() {
  echo "$1" | awk -F'-' '{
    out=$1
    for (i=2; i<=NF; i++) out = out toupper(substr($i,1,1)) substr($i,2)
    print out
  }'
}

# Header
cat <<EOF
version: 1
mapping: $MAPPING
EOF

if [ -n "$AUTH" ]; then
  echo "auth_account: $AUTH"
fi

cat <<EOF
title: "Ship-verify Step 3.6 — $TITLE"

# Generated by plugins/ship-flow/lib/generate-ui-verify-spec.sh from $ENTITY_FILE
# Source: render_fidelity_targets[] in entity ### Hand-off to Plan block
# DO NOT hand-edit; rerun the script if hand-off changes.

checks:
EOF

# Walk render_fidelity_targets[]; emit check per target
echo "$HANDOFF" | awk '
  /render_fidelity_targets:/ { in_rft=1; next }
  /storyboard_frames:|artifact_paths:|^---|^### / { in_rft=0 }
  in_rft && /^[[:space:]]+- selector:/ {
    if (selector != "") emit()
    selector=""; prop=""; expected=""; rd=""
    sub(/^[[:space:]]+- selector:[[:space:]]*/, ""); selector=$0
    next
  }
  in_rft && /^[[:space:]]+css_property:/ { sub(/^[[:space:]]+css_property:[[:space:]]*/, ""); prop=$0; next }
  in_rft && /^[[:space:]]+expected_value:/ { sub(/^[[:space:]]+expected_value:[[:space:]]*/, ""); expected=$0; next }
  in_rft && /^[[:space:]]+rationale_decision:/ { sub(/^[[:space:]]+rationale_decision:[[:space:]]*/, ""); rd=$0; next }
  END { if (selector != "") emit() }

  function emit() {
    # camelCase the property
    n = split(prop, parts, "-")
    cprop = parts[1]
    for (i=2; i<=n; i++) cprop = cprop toupper(substr(parts[i],1,1)) substr(parts[i],2)
    # strip stray quotes from expected
    gsub(/^"|"$/, "", expected)
    gsub(/^"|"$/, "", selector)
    name = (rd != "" ? rd ": " : "") selector " " prop
    print "  - name: \"" name "\""
    print "    selector: \"" selector "\""
    print "    expect:"
    print "      " cprop ": \"" expected "\""
  }
'
