#!/usr/bin/env bash
# import-design-dcs.sh — generate '## Plan Imported Design DCs' section content from
# entity's `### Hand-off to Plan` block. Plan Step 1.6 dispatches this; output goes
# directly into plan.md.
#
# Background: PR #44 G10 made ship-plan Step 1.6 mechanical mapping a doc-level rule;
# the actual mapping was done by LLM. This script makes it deterministic.
#
# Usage:
#   bash import-design-dcs.sh <entity-folder>           # writes to stdout
#   bash import-design-dcs.sh <entity-file>             # single-file (folder-or-flat)
#
# Exit codes:
#   0 — section generated successfully (or design-skipped, emits skip notice)
#   1 — hand-off block invalid (run validate-handoff-schema.sh first)
#   2 — usage error
#
# Output (stdout): ready-to-paste markdown content for plan.md '## Plan Imported Design DCs'.
# Caller appends to plan.md. No file mutation by this script.
#
# Format: structured items mapped 1:1 to ui/e2e DCs with rationale_decision: D{N} preserved.
# Prose-format hand-off → emits skeleton with "MIGRATE FIRST" notice.

set -euo pipefail

TARGET="${1:-}"
[ -z "$TARGET" ] && { echo "ERROR: usage: $0 <entity-folder|entity-file>" >&2; exit 2; }

if [ -d "$TARGET" ]; then
  ENTITY_FILE="${TARGET%/}/design.md"
  [ -f "$ENTITY_FILE" ] || ENTITY_FILE="${TARGET%/}/index.md"
elif [ -f "$TARGET" ]; then
  ENTITY_FILE="$TARGET"
else
  echo "ERROR: target not found: $TARGET" >&2; exit 2
fi

[ -f "$ENTITY_FILE" ] || { echo "ERROR: entity file not found: $ENTITY_FILE" >&2; exit 2; }

# Extract Hand-off to Plan block
HANDOFF=$(awk '/^### Hand-off to Plan/{flag=1} /^<!-- \/section:hand-off-to-plan -->/{flag=0} flag' "$ENTITY_FILE")

if [ -z "$HANDOFF" ]; then
  echo "ERROR: '### Hand-off to Plan' block not found in $ENTITY_FILE" >&2
  echo "ERROR: plan Step 1.6 expects this block — BLOCKER per ship-plan/SKILL.md" >&2
  exit 1
fi

# Detect legacy prose before considering the compact structured-empty path. A
# short legacy hand-off is still content and must never be discarded as empty.
STRUCTURED_HINTS=$(echo "$HANDOFF" | grep -cE '^[[:space:]]+(type|assertion|rationale_decision|selector|css_property|expected_value):' || true)
PROSE_HINTS=$(echo "$HANDOFF" | grep -cE '^[[:space:]]*[0-9]+\.[[:space:]]' || true)

if [ "$STRUCTURED_HINTS" -lt 2 ] && [ "$PROSE_HINTS" -gt 0 ]; then
  cat <<EOF
## Plan Imported Design DCs

<!-- section:plan-imported-design-dcs -->
**Status**: ⚠️ MIGRATE-FIRST — hand-off in legacy prose format. Run:

\`\`\`bash
bash plugins/ship-flow/lib/migrate-design-constraints.sh $ENTITY_FILE
\`\`\`

After migration, rerun this script to populate this section. Plan stage may proceed
inline by reading the prose hand-off directly, but mechanical DC import + verify
Step 3.6 ui-verify integration require structured format.

<!-- /section:plan-imported-design-dcs -->
EOF
  exit 0
fi

# Detect the C4-required but structurally empty case before emitting the normal
# multi-table body. Every declared importable collection must be an explicit
# empty array; a missing, prose, null, or unparsed structure stays on the normal
# fail-loud/migration path instead of being guessed empty.
IMPORTABLE_DECL_COUNT=$(echo "$HANDOFF" | grep -cE '^[[:space:]]*(design_constraints|visible_surface_map|render_fidelity_targets|whole_page_visual_targets):' || true)
EXPLICIT_EMPTY_IMPORTABLE_COUNT=$(echo "$HANDOFF" | grep -cE '^[[:space:]]*(design_constraints|visible_surface_map|render_fidelity_targets|whole_page_visual_targets):[[:space:]]*\[[[:space:]]*\][[:space:]]*$' || true)
IMPORTABLE_ITEM_COUNT=$(echo "$HANDOFF" | awk '
  /^[[:space:]]*(design_constraints|visible_surface_map|render_fidelity_targets|whole_page_visual_targets):/ { in_importable=1; next }
  /^[[:space:]]*(open_decisions|artifact_paths|storyboard_frames):/ { in_importable=0 }
  in_importable && /^[[:space:]]*-[[:space:]]*[A-Za-z_]+:/ { n++ }
  END { print n+0 }
')

if ! echo "$HANDOFF" | grep -qE '^[[:space:]]*-?[[:space:]]*design-skipped:[[:space:]]*true' \
  && [ "$IMPORTABLE_DECL_COUNT" -gt 0 ] \
  && [ "$IMPORTABLE_DECL_COUNT" -eq "$EXPLICIT_EMPTY_IMPORTABLE_COUNT" ] \
  && [ "$IMPORTABLE_ITEM_COUNT" -eq 0 ]; then
  cat <<'EOF'
## Plan Imported Design DCs

<!-- section:plan-imported-design-dcs -->
**Status**: no structured design DCs or visual targets to import.
<!-- /section:plan-imported-design-dcs -->
EOF
  exit 0
fi

# Header
cat <<'HEADER'
## Plan Imported Design DCs

<!-- section:plan-imported-design-dcs -->
<!-- Generated by plugins/ship-flow/lib/import-design-dcs.sh from entity's ### Hand-off to Plan block. Do not hand-edit; rerun the script if the source hand-off changes. -->

HEADER

# Design-skipped short-circuit
if echo "$HANDOFF" | grep -qE '^[[:space:]]*-?[[:space:]]*design-skipped:[[:space:]]*true'; then
  cat <<'EOF'
**Status**: design-skipped (entity has `affects_ui: false`; design stage bypassed by shape Phase 8).

No design DCs to import. Plan proceeds without UI/render-fidelity DC imports.

<!-- /section:plan-imported-design-dcs -->
EOF
  exit 0
fi

# Structured-format extraction
echo "### Imported design_constraints"
echo ""
echo "| # | Type | Assertion | Rationale (D{N}) | Source artifact |"
echo "|---|---|---|---|---|"

DC_SOURCE_COUNT=$(echo "$HANDOFF" | awk '
  /design_constraints:/ { in_dc=1; next }
  /open_decisions:|render_fidelity_targets:|artifact_paths:|^---|^### / { in_dc=0 }
  in_dc && /^[[:space:]]*-[[:space:]]*(type|assertion):/ { n++ }
  END { print n+0 }
')

# Awk-driven extraction: walk the design_constraints[] section, emit one row per item
echo "$HANDOFF" | awk -v expected="$DC_SOURCE_COUNT" '
  function emit() {
    if (started) {
      if (type == "" || assertion == "" || rd == "") {
        print "ERROR: malformed design_constraints[] item; expected type, assertion, rationale_decision" > "/dev/stderr"
        exit 1
      }
      print "| " (++n) " | " type " | " assertion " | " rd " | " sa " |"
    }
  }
  /design_constraints:/ { in_dc=1; next }
  /open_decisions:|render_fidelity_targets:|artifact_paths:|^---|^### / { in_dc=0 }
  in_dc && /^[[:space:]]*-[[:space:]]*type:/ {
    emit()
    started=1
    type=""; assertion=""; rd=""; sa=""
    sub(/^[[:space:]]*-[[:space:]]*type:[[:space:]]*/, ""); type=$0
    next
  }
  in_dc && /^[[:space:]]*-[[:space:]]*assertion:/ {
    emit()
    started=1
    type=""; assertion=""; rd=""; sa=""
    sub(/^[[:space:]]*-[[:space:]]*assertion:[[:space:]]*/, ""); assertion=$0
    next
  }
  in_dc && /^[[:space:]]+assertion:/ { sub(/^[[:space:]]+assertion:[[:space:]]*/, ""); assertion=$0 }
  in_dc && /^[[:space:]]+rationale_decision:/ { sub(/^[[:space:]]+rationale_decision:[[:space:]]*/, ""); rd=$0 }
  in_dc && /^[[:space:]]+source_artifact:/ { sub(/^[[:space:]]+source_artifact:[[:space:]]*/, ""); sa=$0 }
  END {
    emit()
    if (n != expected) {
      print "ERROR: imported design_constraints count mismatch; source=" expected ", imported=" n > "/dev/stderr"
      exit 1
    }
  }
'

echo ""
echo "### Imported visible_surface_map"
echo ""
echo "| # | ID | Type | Route | Selector Hint | Visible When | Coverage | Mapped By | Rationale (D{N}) | N/A Rationale |"
echo "|---|---|---|---|---|---|---|---|---|---|"

echo "$HANDOFF" | awk '
  function clean(value, q) {
    sub(/^[[:space:]]+/, "", value)
    sub(/[[:space:]]+$/, "", value)
    q=sprintf("%c", 39)
    if ((substr(value, 1, 1) == "\"" && substr(value, length(value), 1) == "\"") ||
        (substr(value, 1, 1) == q && substr(value, length(value), 1) == q)) {
      value=substr(value, 2, length(value) - 2)
    }
    return value
  }
  function set_field(key, value) {
    value=clean(value)
    if (key == "id") id=value
    else if (key == "surface_type") surface_type=value
    else if (key == "route") route=value
    else if (key == "selector_hint") selector_hint=value
    else if (key == "visible_when") visible_when=value
    else if (key == "intent_summary") intent_summary=value
    else if (key == "coverage") coverage=value
    else if (key == "mapped_by") mapped_by=value
    else if (key == "rationale_decision") rd=value
    else if (key == "na_rationale") na=value
  }
  function parse_field(line) {
    sub(/^[[:space:]]*-[[:space:]]*/, "", line)
    sub(/^[[:space:]]+/, "", line)
    key=line
    sub(/:.*/, "", key)
    value=line
    sub(/^[^:]+:[[:space:]]*/, "", value)
    set_field(key, value)
  }
  function fail(msg) {
    print "ERROR: malformed visible_surface_map[] item: " msg > "/dev/stderr"
    bad=1
  }
  function emit() {
    if (!started) return
    if (id == "") fail("missing id")
    if (id != "" && id !~ /^[a-z0-9][a-z0-9-]*$/) fail(id " invalid id")
    if (surface_type !~ /^(region|control|state_indicator|semantic_badge)$/) fail(id " invalid or missing surface_type")
    if (route == "") fail(id " missing route")
    if (selector_hint == "") fail(id " missing selector_hint")
    if (visible_when == "") fail(id " missing visible_when")
    if (intent_summary == "") fail(id " missing intent_summary")
    if (coverage !~ /^(mapped|explicit_na|deferred_blocker)$/) fail(id " invalid or missing coverage")
    if (rd !~ /^D[0-9]+$/) fail(id " missing rationale_decision")
    if (coverage == "mapped" && mapped_by == "") fail(id " coverage:mapped missing mapped_by")
    if (coverage == "explicit_na" && na == "") fail(id " coverage:explicit_na missing na_rationale")
    if (!bad) print "| " (++n) " | `" id "` | " surface_type " | `" route "` | `" selector_hint "` | " visible_when " | " coverage " | " mapped_by " | " rd " | " na " |"
  }
  /^[[:space:]]*visible_surface_map:/ { in_vsm=1; next }
  in_vsm && /^[[:space:]]*(render_fidelity_targets:|whole_page_visual_targets:|storyboard_frames:|open_decisions:|artifact_paths:|---|### )/ { in_vsm=0 }
  in_vsm && /^[[:space:]]*-[[:space:]]*[A-Za-z_]+:/ {
    emit()
    started=1
    id=surface_type=route=selector_hint=visible_when=intent_summary=coverage=mapped_by=rd=na=""
    parse_field($0)
    next
  }
  in_vsm && started && /^[[:space:]]+[A-Za-z_]+:/ { parse_field($0) }
  END {
    emit()
    exit bad
  }
'

echo ""
echo "### Imported render_fidelity_targets"
echo ""
echo "| # | Selector | CSS Property | Expected Value | Rationale (D{N}) |"
echo "|---|---|---|---|---|"

echo "$HANDOFF" | awk '
  /render_fidelity_targets:/ { in_rft=1; next }
  /whole_page_visual_targets:|storyboard_frames:|artifact_paths:|^---|^### / { in_rft=0 }
  in_rft && /^[[:space:]]*-[[:space:]]*selector:/ {
    if (selector != "") print "| " (++n) " | `" selector "` | " prop " | " expected " | " rd " |"
    selector=""; prop=""; expected=""; rd=""
    sub(/^[[:space:]]*-[[:space:]]*selector:[[:space:]]*/, ""); selector=$0
  }
  in_rft && /^[[:space:]]+css_property:/ { sub(/^[[:space:]]+css_property:[[:space:]]*/, ""); prop=$0 }
  in_rft && /^[[:space:]]+expected_value:/ { sub(/^[[:space:]]+expected_value:[[:space:]]*/, ""); expected=$0 }
  in_rft && /^[[:space:]]+rationale_decision:/ { sub(/^[[:space:]]+rationale_decision:[[:space:]]*/, ""); rd=$0 }
  END { if (selector != "") print "| " (++n) " | `" selector "` | " prop " | " expected " | " rd " |" }
'

echo ""
echo ""
echo "### Imported whole_page_visual_targets"
echo ""
echo "| # | Route | Reference Artifact | Capture | Threshold | Rationale (D{N}) |"
echo "|---|---|---|---|---|---|"

echo "$HANDOFF" | awk '
  /whole_page_visual_targets:/ { in_wp=1; next }
  /storyboard_frames:|artifact_paths:|^---|^### / { in_wp=0 }
  in_wp && /^[[:space:]]*-[[:space:]]*route:/ {
    if (route != "") print "| " (++n) " | `" route "` | " ref " | " capture " | " threshold " | " rd " |"
    route=""; ref=""; capture=""; threshold=""; rd=""
    sub(/^[[:space:]]*-[[:space:]]*route:[[:space:]]*/, ""); route=$0
  }
  in_wp && /^[[:space:]]+reference_artifact:/ { sub(/^[[:space:]]+reference_artifact:[[:space:]]*/, ""); ref=$0 }
  in_wp && /^[[:space:]]+capture:/ { sub(/^[[:space:]]+capture:[[:space:]]*/, ""); capture=$0 }
  in_wp && /^[[:space:]]+threshold:/ { sub(/^[[:space:]]+threshold:[[:space:]]*/, ""); threshold=$0 }
  in_wp && /^[[:space:]]+rationale_decision:/ { sub(/^[[:space:]]+rationale_decision:[[:space:]]*/, ""); rd=$0 }
  END { if (route != "") print "| " (++n) " | `" route "` | " ref " | " capture " | " threshold " | " rd " |" }
'

echo ""
echo "**Wave assignment**: each constraint anchored to the task wave touching the affected component;"
echo "render-fidelity targets default to W0 for token-level checks, task wave for component-level;"
echo "whole-page visual targets default to the integration wave or affected route wave."
echo ""
echo "**Verify backend**: ship-verify Step 3.6 dispatches \`Skill: ship-flow:ui-verify\` with the render_fidelity_targets[]"
echo "section above as input YAML; ship-verify Step 3.6.1 captures full-page screenshots for whole_page_visual_targets[] — no manual transcription required."
echo ""
echo "<!-- /section:plan-imported-design-dcs -->"
