#!/usr/bin/env bash
# import-design-dcs.sh — generate '## Plan Imported Design DCs' section content from
# entity's `### Hand-off to Plan` block. Plan Step 1.6 dispatches this; output goes
# directly into plan.md.
#
# Background: PR #44 G10 made ship-plan Step 1.6 mechanical mapping a doc-level rule;
# the actual mapping was done by LLM. This script makes it deterministic.
#
# Usage:
#   bash import-design-dcs.sh <entity-folder>           # writes to stdout
#   bash import-design-dcs.sh <entity-file>             # single-file (folder-or-flat)
#
# Exit codes:
#   0 — section generated successfully (or design-skipped, emits skip notice)
#   1 — hand-off block invalid (run validate-handoff-schema.sh first)
#   2 — usage error
#
# Output (stdout): ready-to-paste markdown content for plan.md '## Plan Imported Design DCs'.
# Caller appends to plan.md. No file mutation by this script.
#
# Format: structured items mapped 1:1 to ui/e2e DCs with rationale_decision: D{N} preserved.
# Prose-format hand-off → emits skeleton with "MIGRATE FIRST" notice.

set -euo pipefail

TARGET="${1:-}"
[ -z "$TARGET" ] && { echo "ERROR: usage: $0 <entity-folder|entity-file>" >&2; exit 2; }

if [ -d "$TARGET" ]; then
  ENTITY_FILE="${TARGET%/}/README.md"
  [ -f "$ENTITY_FILE" ] || ENTITY_FILE="${TARGET%/}/design.md"
elif [ -f "$TARGET" ]; then
  ENTITY_FILE="$TARGET"
else
  echo "ERROR: target not found: $TARGET" >&2; exit 2
fi

[ -f "$ENTITY_FILE" ] || { echo "ERROR: entity file not found: $ENTITY_FILE" >&2; exit 2; }

# Extract Hand-off to Plan block
HANDOFF=$(awk '/^### Hand-off to Plan/{flag=1} /^<!-- \/section:hand-off-to-plan -->/{flag=0} flag' "$ENTITY_FILE")

if [ -z "$HANDOFF" ]; then
  echo "ERROR: '### Hand-off to Plan' block not found in $ENTITY_FILE" >&2
  echo "ERROR: plan Step 1.6 expects this block — BLOCKER per ship-plan/SKILL.md" >&2
  exit 1
fi

# Header
cat <<'HEADER'
## Plan Imported Design DCs

<!-- section:plan-imported-design-dcs -->
<!-- Generated by plugins/ship-flow/lib/import-design-dcs.sh from entity's ### Hand-off to Plan block. Do not hand-edit; rerun the script if the source hand-off changes. -->

HEADER

# Design-skipped short-circuit
if echo "$HANDOFF" | grep -qE '^[[:space:]]*-?[[:space:]]*design-skipped:[[:space:]]*true'; then
  cat <<'EOF'
**Status**: design-skipped (entity has `affects_ui: false`; design stage bypassed by shape Phase 8).

No design DCs to import. Plan proceeds without UI/render-fidelity DC imports.

<!-- /section:plan-imported-design-dcs -->
EOF
  exit 0
fi

# Format detection
STRUCTURED_HINTS=$(echo "$HANDOFF" | grep -cE '^[[:space:]]+(type|assertion|rationale_decision|selector|css_property|expected_value):' || true)
PROSE_HINTS=$(echo "$HANDOFF" | grep -cE '^[[:space:]]*[0-9]+\.[[:space:]]' || true)

if [ "$STRUCTURED_HINTS" -lt 2 ] && [ "$PROSE_HINTS" -gt 2 ]; then
  cat <<EOF
**Status**: ⚠️ MIGRATE-FIRST — hand-off in legacy prose format. Run:

\`\`\`bash
bash plugins/ship-flow/lib/migrate-design-constraints.sh $ENTITY_FILE
\`\`\`

After migration, rerun this script to populate this section. Plan stage may proceed
inline by reading the prose hand-off directly, but mechanical DC import + verify
Step 3.6 ui-verify integration require structured format.

<!-- /section:plan-imported-design-dcs -->
EOF
  exit 0
fi

# Structured-format extraction
echo "### Imported design_constraints"
echo ""
echo "| # | Type | Assertion | Rationale (D{N}) | Source artifact |"
echo "|---|---|---|---|---|"

# Awk-driven extraction: walk the design_constraints[] section, emit one row per item
echo "$HANDOFF" | awk '
  /design_constraints:/ { in_dc=1; next }
  /render_fidelity_targets:|artifact_paths:|open_decisions:|^---|^### / { in_dc=0 }
  in_dc && /^[[:space:]]+- type:/ {
    if (assertion != "") print "| " (++n) " | " type " | " assertion " | " rd " | " sa " |"
    type=""; assertion=""; rd=""; sa=""
    sub(/^[[:space:]]+- type:[[:space:]]*/, ""); type=$0
  }
  in_dc && /^[[:space:]]+assertion:/ { sub(/^[[:space:]]+assertion:[[:space:]]*/, ""); assertion=$0 }
  in_dc && /^[[:space:]]+rationale_decision:/ { sub(/^[[:space:]]+rationale_decision:[[:space:]]*/, ""); rd=$0 }
  in_dc && /^[[:space:]]+source_artifact:/ { sub(/^[[:space:]]+source_artifact:[[:space:]]*/, ""); sa=$0 }
  END { if (assertion != "") print "| " (++n) " | " type " | " assertion " | " rd " | " sa " |" }
'

echo ""
echo "### Imported render_fidelity_targets"
echo ""
echo "| # | Selector | CSS Property | Expected Value | Rationale (D{N}) |"
echo "|---|---|---|---|---|"

echo "$HANDOFF" | awk '
  /render_fidelity_targets:/ { in_rft=1; next }
  /storyboard_frames:|artifact_paths:|^---|^### / { in_rft=0 }
  in_rft && /^[[:space:]]+- selector:/ {
    if (selector != "") print "| " (++n) " | `" selector "` | " prop " | " expected " | " rd " |"
    selector=""; prop=""; expected=""; rd=""
    sub(/^[[:space:]]+- selector:[[:space:]]*/, ""); selector=$0
  }
  in_rft && /^[[:space:]]+css_property:/ { sub(/^[[:space:]]+css_property:[[:space:]]*/, ""); prop=$0 }
  in_rft && /^[[:space:]]+expected_value:/ { sub(/^[[:space:]]+expected_value:[[:space:]]*/, ""); expected=$0 }
  in_rft && /^[[:space:]]+rationale_decision:/ { sub(/^[[:space:]]+rationale_decision:[[:space:]]*/, ""); rd=$0 }
  END { if (selector != "") print "| " (++n) " | `" selector "` | " prop " | " expected " | " rd " |" }
'

echo ""
echo "**Wave assignment**: each constraint anchored to the task wave touching the affected component;"
echo "render-fidelity targets default to W0 for token-level checks, task wave for component-level."
echo ""
echo "**Verify backend**: ship-verify Step 3.6 dispatches \`Skill: ui-verify\` with the render_fidelity_targets[]"
echo "section above as input YAML — no manual transcription required."
echo ""
echo "<!-- /section:plan-imported-design-dcs -->"
